Repository kubediag/kubediag, pull requests merged in 2021-07, with the labels that each got.

#75 Support installation via Helm chart
  README.md
  config/deploy/manifests.yaml
  config/manager/kubediag.yaml
  config/rbac/kustomization.yaml
Labels: kind/documentation

#78 Support address of DNS type in Operation registration
  Dockerfile.arm64
  api/v1/operation_types.go
  api/v1/operation_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/diagnosis.kubediag.org_operations.yaml
  config/deploy/manifests.yaml
  docs/api/operation.md
  docs/design/graph-based-pipeline.md
  docs/design/processor.md
  go.mod
  go.sum
  pkg/executor/executor.go
  samples/http-operation/manifests/operation.yaml
  vendor/github.com/asaskevich/govalidator/.gitignore
  vendor/github.com/asaskevich/govalidator/.travis.yml
  vendor/github.com/asaskevich/govalidator/CONTRIBUTING.md
  vendor/github.com/asaskevich/govalidator/LICENSE
  vendor/github.com/asaskevich/govalidator/README.md
  vendor/github.com/asaskevich/govalidator/arrays.go
  vendor/github.com/asaskevich/govalidator/converter.go
  vendor/github.com/asaskevich/govalidator/doc.go
  vendor/github.com/asaskevich/govalidator/error.go
  vendor/github.com/asaskevich/govalidator/go.mod
  vendor/github.com/asaskevich/govalidator/numerics.go
  vendor/github.com/asaskevich/govalidator/patterns.go
  vendor/github.com/asaskevich/govalidator/types.go
  vendor/github.com/asaskevich/govalidator/utils.go
  vendor/github.com/asaskevich/govalidator/validator.go
  vendor/github.com/asaskevich/govalidator/wercker.yml
  vendor/modules.txt
Labels: kind/feature, priority/important-soon

#81 Add design document for elasticsearch collector
  docs/processors/elasticsearch-collector.md
Labels: kind/documentation

#85 Fix circleci config
  .circleci/config.yml
  Makefile
Labels: kind/cleanup

#79 Add design document for script runner
  docs/design/script-runner.md
Labels: kind/documentation

#86 Add code verification in circleci
  .circleci/config.yml
Labels: kind/cleanup

#83 Implement script runner
  api/v1/operation_types.go
  api/v1/operation_webhook.go
  api/v1/trigger_webhook.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/diagnosis.kubediag.org_operations.yaml
  config/deploy/container_collector.yaml
  config/deploy/containerd_goroutine_collector.yaml
  config/deploy/core_file_profiler.yaml
  config/deploy/docker_info_collector.yaml
  config/deploy/dockerd_goroutine_collector.yaml
  config/deploy/go_profiler.yaml
  config/deploy/manifests.yaml
  config/deploy/mountinfo_collector.yaml
  config/deploy/node_cordon.yaml
  config/deploy/pod_detail_collector.yaml
  config/deploy/pod_list_collector.yaml
  config/deploy/process_collector.yaml
  config/samples/corefile_profiler.yaml
  config/samples/disk_usage_script.yaml
  main.go
  pkg/controllers/diagnosis_controller.go
  pkg/controllers/operation_controller.go
  pkg/controllers/trigger_controller.go
  pkg/executor/executor.go
  pkg/features/features.go
  pkg/processors/executor/command_executor.go
  pkg/processors/register/register.go
Labels: kind/feature
