Repository kubediag/kubediag, pull requests merged in 2022-08, with the labels that each got.

#149 Create a CommonEvent on receiving PagerDuty message
  PROJECT
  api/v1/commonevent_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/diagnosis.kubediag.org_commonevents.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_commonevents.yaml
  config/crd/patches/webhook_in_commonevents.yaml
  config/deploy/manifests.yaml
  config/rbac/commonevent_editor_role.yaml
  config/rbac/commonevent_viewer_role.yaml
  config/rbac/role.yaml
  hack/boilerplate.go.txt
  main.go
  pkg/controllers/diagnosis_controller.go
  pkg/controllers/operation_controller.go
  pkg/features/features.go
  pkg/garbagecollection/commonevent_reaper.go
  pkg/garbagecollection/diagnosis_reaper.go
  pkg/pagerdutyeventer/pagerdutyeventer.go
Labels: kind/api-change

#150 Add labels to manage CommonEvent
  pkg/pagerdutyeventer/pagerdutyeventer.go
Labels: kind/feature

#151 Add parameters in alertmanager trigger
  pkg/alertmanager/alertmanager.go
Labels: kind/feature

#152 Add API documentation generation in Makefile
  Makefile
  docs/api/api-docs.md
  docs/api/gen-crd-api-reference-docs/example-config.json
  docs/api/gen-crd-api-reference-docs/template/members.tpl
  docs/api/gen-crd-api-reference-docs/template/pkg.tpl
  docs/api/gen-crd-api-reference-docs/template/placeholder.go
  docs/api/gen-crd-api-reference-docs/template/type.tpl
Labels: kind/documentation

#158 Update CommonEvent status if it is recently created
  pkg/pagerdutyeventer/pagerdutyeventer.go
Labels: kind/feature
